name: Test & Deploy

on:
  push:
    branches:
    - master

jobs:
  test:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: Setup
      run: |
        npm i
        export NODE_OPTIONS=--max_old_space_size=2048
    - name: Lint
      run: npx grunt lint
    - name: Unit Tests
      run: |
        npx grunt test
        sudo npx grunt testnodeconsumer
    - name: Production Build
      run: npx grunt prod
    - name: UI Tests
      run: xvfb-run --server-args="-screen 0 1200x800x24" npx grunt testui
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        PERSONAL_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./build/prod
